// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABc8FTlTpH7PkHIm07Wr5CqbZ1fdnsWcw',
    appId: '1:873010238311:web:447e56ea1ef50d95de95c2',
    messagingSenderId: '873010238311',
    projectId: 'app-receitas-810eb',
    authDomain: 'app-receitas-810eb.firebaseapp.com',
    storageBucket: 'app-receitas-810eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx1SEmDaJ88QOOGyBQT7R04ARqpsoCbVo',
    appId: '1:873010238311:android:068e7b4b5a07c0dfde95c2',
    messagingSenderId: '873010238311',
    projectId: 'app-receitas-810eb',
    storageBucket: 'app-receitas-810eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhuLEefudto-XU2cR-h8xbU7UpqyEDvR0',
    appId: '1:873010238311:ios:bbb498ca87b58526de95c2',
    messagingSenderId: '873010238311',
    projectId: 'app-receitas-810eb',
    storageBucket: 'app-receitas-810eb.firebasestorage.app',
    iosBundleId: 'com.example.matc89AplicativoReceitas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhuLEefudto-XU2cR-h8xbU7UpqyEDvR0',
    appId: '1:873010238311:ios:bbb498ca87b58526de95c2',
    messagingSenderId: '873010238311',
    projectId: 'app-receitas-810eb',
    storageBucket: 'app-receitas-810eb.firebasestorage.app',
    iosBundleId: 'com.example.matc89AplicativoReceitas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABc8FTlTpH7PkHIm07Wr5CqbZ1fdnsWcw',
    appId: '1:873010238311:web:6932e4eaf19ecc59de95c2',
    messagingSenderId: '873010238311',
    projectId: 'app-receitas-810eb',
    authDomain: 'app-receitas-810eb.firebaseapp.com',
    storageBucket: 'app-receitas-810eb.firebasestorage.app',
  );

}